### ISSUE TITLE
analytics on various parameters e.g. how many people still LGTM in comments

### ISSUE THREAD

**Issue by refack** [nodejs/node-core-utils#102]
Seems like it's an old custom, but I think it's cute.
![image](https://user-images.githubusercontent.com/96947/32676056-26b0ca96-c627-11e7-8eeb-65058e9f9d7f.png)

**Comment by refack** [comment]
H/T @bnb

**Comment by MylesBorins** [comment]
I'm -1 on this

People should have to be explicit on this. We don't consider shipit an official LGTM for core commits afaik

**Comment by Tiriel** [comment]
It is cute indeed, but I'm -1 too.
The only other case I'd accept with LGTM is "SGTM", because it's explicit. But I don't think we should extend too much on the accepted cases.

**Comment by joyeecheung** [comment]
@Tiriel I wouldn't accept `SGTM` either because that implies the person has not actually reviewed i.e LOOKed into the code, therefore they don't count as reviewers.

**Comment by joyeecheung** [comment]
Also in my understanding, reviewers should be able to backport or fix regressions when the original author is not available. SGTM or shipit do not really imply that either..

**Comment by refack** [comment]
This makes me think of an actual but tangential idea. Report analytics on the versions parameter (such as how many people still LGTM in comments).

If you don't mind I'll pivot this issue and self assign.

### New subject: analytics
