### ISSUE TITLE
PRChecker: Check that semver-major commits have an explanation of breaking changes

### ISSUE THREAD

**Issue by refack** [nodejs/node-core-utils#108]
Refs: https://github.com/nodejs/node/pull/16846

**Comment by Tiriel** [comment]
Funnily enough, I saw this discussion, and thought "When this lands, this will be a perfect job for the pr_checker".

Anyway: :+1:

**Comment by joyeecheung** [comment]
To me this is not the job for pr checker, but the job for core-validate-commit.

**Comment by Tiriel** [comment]
True! I had forgotten we had other tools :smile:

**Comment by refack** [comment]
> To me this is not the job for pr checker, but the job for core-validate-commit: checking commit messages.

> True! I had forgotten we had other tools

It's not a trivial separation 🤔 - this might not be a simple formatting rule like what `core-validate-commit` check, it might need to live in the PR description (like `Fixes`) and require the author's to help...

As I see it `core-validate-commit`:
1) Checks formatting rules - all of which the lander can fix (maybe even automatically)
2) Is run last in the landing process - just before a `git push` - so it is kind of late to stop the land process and ask for new information

IMHO such a failure should block the PR from being ready to land earlier, so that the lander could ask for more information from the author.

**Comment by cPhost** [comment]
@refack for now we should probably wait for `Breaking: ` and the length requirement to land in core first or something like that and then maybe we can implement this?

**Comment by refack** [comment]
@cPhost in term of ❌  / ✔️ I agree.
I also think that having the tool report on the rules for uncommon cases would be very helpful... let's think about this, try to find a smart way to do that.
