### ISSUE TITLE
get-metadata: Git Bash for Windows nits

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#112]
Windows 7 x64
Node.js 9.2.0
get-metadata 1.6.1

Please, compare the outputs in a `cmd.exe`:

![cmd](https://user-images.githubusercontent.com/10393198/32815289-f8ff67f4-c9bb-11e7-90f5-c67e5e553bdd.png)

and Git Bash for Windows:

![git-bash](https://user-images.githubusercontent.com/10393198/32815290-f91aaf14-c9bb-11e7-808e-52777a82c776.png)

1. Git Bash output lacks colors.
2. Git Bash output duplicates metadata.

**Comment by cPhost** [comment]
@vsemozhetbyt the color is probably because of git bash.
Definitely duplication colors is a bug which should probably be related to git bash too.

**Comment by cPhost** [comment]
@vsemozhetbyt can you let me know what does this cmd
`node -p -e "Boolean(process.stdout.isTTY)"`
prints out in Git Bash.

**Comment by vsemozhetbyt** [comment]
@cPhost 
```console
$ node -p -e "Boolean(process.stdout.isTTY)"
true
```

**Comment by cPhost** [comment]
Basically the only way the metadata could be outputted to terminal two time is if 
`if(!process.stdout.isTTY)` which in this case we confirmed should not and the other time with
`lib/cli` module. which works as expected as git bash is a terminal.

**Comment by vsemozhetbyt** [comment]
@cPhost I suppose it is connected with this note [here](https://github.com/nodejs/node/blob/master/BUILDING.md#supported-platforms-1):
> Note: On Windows, running Node.js in windows terminal emulators like mintty requires the usage of winpty for Node's tty channels to work correctly (e.g. winpty node.exe script.js). In "Git bash" if you call the node shell alias (node without the .exe extension), winpty is used automatically.

With `node.exe`:
```console
$ node.exe -p -e "Boolean(process.stdout.isTTY)"
false
```

**Comment by joyeecheung** [comment]
Does redirecting work with Git bash? We can probably somehow check that in the code an don't write to stdout if that's the case...

**Comment by joyeecheung** [comment]
Or is it a bug of node core? Shouldn't it be `false`?

**Comment by vsemozhetbyt** [comment]
FWIW, with `winpty` and full filename both nits are fixed:

![winpty](https://user-images.githubusercontent.com/10393198/32816543-e15935de-c9c1-11e7-905d-af04c97b8205.png)

**Comment by cPhost** [comment]
There was a bug reported in core for this which was closed. 
The reason this happens is that Git Bash is using (maybe using?) pipes.

**Comment by cPhost** [comment]
Finally we can add note to readme about this.
