### ISSUE TITLE
Work out PR number for head branch

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-core-utils#119]
It'd be nice if I could do `get-metadata` (or `get-metadata @`) if I'm on a fork branch with an open PR.

Could do something like:

```bash
# Get the remote url of the upstream branch (if it exists).
remote=$(git remote get-url $(git rev-parse --abbrev-ref --symbolic-full-name @{u} | cut -d / -f 1))
branch=$(git symbolic-ref --short HEAD) # Or branch parameter passed.

# Convert to https:// syntax if it's ssh syntax (git@github.com)

# Work out what PR has that as a base branch

# Pass PR number through to the rest of get-metadata.
```

**Comment by joyeecheung** [comment]
https://github.com/nodejs/node-core-utils/pull/106 kinda needs this as well, although that one is for landing PRs that are not necessarily opened by the people landing them. I am thinking a `git node config` command to associate remote/branch settings so the configuration persists and we don't have to pass the parameter all the time.

**Comment by joyeecheung** [comment]
Also it would be convenient if I can `git node pr --open` from the current branch, a bit like `git cl upload` of chromium/v8

**Comment by gibfahn** [comment]
>I am thinking a git node config command to associate remote/branch settings so the configuration persists and we don't have to pass the parameter all the time.

Config option makes sense, although I think working it out from the upstream is a good fallback.

>git node pr --open from the current branch, which open the PR and associate the branches for you, a bit like git cl upload of chromium/v8.

What do you mean by associating the branches for you? I can see that you could automate the "raise PR from fork/mybranch against upstream/master with this comment".

**Comment by evanlucas** [comment]
@joyeecheung I had previously worked on something to kick off a CI run at https://github.com/evanlucas/nodejs-ci-ctl

**Comment by joyeecheung** [comment]
@evanlucas Awesome, I will see if I can integrate that into the git commands
