### ISSUE TITLE
get-metadata: should we accept "Fixes" and "Refs" without ":"?

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#127]
Refs: in the https://github.com/nodejs/node/pull/17295, the `Fixes https://github.com/nodejs/node/issues/17294` commit message line was not included in the metadata.

**Comment by joyeecheung** [comment]
I am a bit afraid this would give some false positives and we have to end up with struggling with natural language processing. So the easiest solution is: if people don't follow the format, just ignore it.

**Comment by vsemozhetbyt** [comment]
@joyeecheung I am a bit concerned that people can use GitHub syntax that does not require `:`

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by Tiriel** [comment]
Well, they might indeed, but the syntax only works when the branch is merge according to the doc you linked, I don't know if it works with our process.

Anyway, I'm +1 with @joyeecheung , the formatting exists for a reason IMHO, I don't think we should make allowance or we risk having more problems than now.

**Comment by targos** [comment]
is it detected by a regexp now?

**Comment by joyeecheung** [comment]
@targos Yea it's deteced by regular expressions in `lib/links.js`, with some JSdom queries to get the URL out of the `href` attributes.

**Comment by gibfahn** [comment]
>That said, I'm not sure we should encourage this syntax. Maybe it could be normalized by get-metadata.

Agreed, having `get-metadata` be forgiving in what it accepts is good, but it should only output the one canonical form.

**Comment by codebytere** [comment]
i'd say we should close this - I see no real reason to deviate from syntax we've been adhering to for years
