### ISSUE TITLE
Error out on young PRs without fast-track label

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#131]
If a PR has a `fast-track` label on it, it should not be complained about. Right now there is a warning sign in case the PR is younger than 48 hours (do we check 72 hours on the weekend by the way?). But if the label is applied, that should not warn out of my perspective. And if the label is not applied, I would expect a error instead of just a warning.

**Comment by cPhost** [comment]
@BridgeAR we do check for 72 hours on weekdays. 

> And if the label is not applied, I would expect a error instead of just a warning.

I dont think we can detect if a PR needs fast track 

Can you elaborate more on what you need error for or don not have warning for.

**Comment by apapirovski** [comment]
> I dont think we can detect if a PR needs fast track

We definitely can, that's what the `fast-track` label is for.

**Comment by cPhost** [comment]
@apapirovski we do warn in case when PR has `fast-track` label i think @BridgeAR was talking about detecting if PR needs `fast-tracking`

(Correct me if am wrong)

**Comment by apapirovski** [comment]
In that case there doesn't seem to be much to do with this issue? I think @BridgeAR is just asking for the functionality that was implemented in https://github.com/nodejs/node-core-utils/pull/104/files

**Comment by BridgeAR** [comment]
What I am asking for is a `error` instead of a `warning`. It is of course trivial to change that but I would really like to enforce using the label.

**Comment by mmarchini** [comment]
`ncu` handles fast-track properly today
