### ISSUE TITLE
Detect first contributions

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#132]
It would be neat if it would log something on the console that the user is actually a first timer. That way we can write some nice things for the user after landing the commit and closing the PR.

I know that is visible in the PR itself but you have to pay attention to it and as soon as the PR landed, the label will be gone as well. So adding it to the console is probably best.

**Comment by tniessen** [comment]
Is there an API to check this? The only way I can think of is to query commits by the given author, and assume they are a first-time contributor if no commit with a matching author field exists.

**Comment by joyeecheung** [comment]
The logic is already implemented, we just need to move it to `pr_data.js` and log it out there

https://github.com/nodejs/node-core-utils/blob/master/lib/pr_checker.js#L258-L261
