### ISSUE TITLE
Detect double `Refs` and `Fixes` entries.

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#133]
Right now if the tool is used as it the commit message that is generated duplicates `Refs` and `Fixes` entries by amending those blindly. We might come up with a way to remove those - and verify that they are identical with the ones being amended (and if not, it should result in an error).

**Comment by joyeecheung** [comment]
BTW https://github.com/nodejs/node-core-utils/pull/106/files#diff-806602ca40b9756be13878981c68b536R109 does handle this in case there are already urls present in the commit message without metadata.

**Comment by joyeecheung** [comment]
It's fixed by the new `git-node` command, although it still does not fix the following case:

```
Fixes: #XXXX   # put by the author

Something something...

Fixes: https://github.com/nodejs/node/issue/XXXX # generated by us
```

**Comment by BridgeAR** [comment]
@joyeecheung that was the case that I meant ^^.

**Comment by codebytere** [comment]
Will be closed by https://github.com/nodejs/node-core-utils/pull/478
