### ISSUE TITLE
Add a collaborator's contact to a message by login

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#140]
There are cases where one has to add a collaborator manually to the metadata since our heuristics are limited. It's worth adding a command or something that allows the users to add a collaborator there by specifying a login. Maybe something like

```
get-metadata -i msg.txt --add joyeecheung -f msg.txt
```

**Comment by tniessen** [comment]
When's that necessary? Shouldn't reviews be properly resolved using the GH API already?

**Comment by joyeecheung** [comment]
@tniessen For example when the LGTM is given via emails https://github.com/nodejs/node/pull/18125#issuecomment-357518819 . That can be fixed differently, of course, but I think we will keep bumping into edge cases like this so it's nice to have a command for adding reviewers.
