### ISSUE TITLE
Check that a semver-major PR has at least a CITGM CI run

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#141]
Refs: https://github.com/nodejs/node/pull/18210

On a side note, we should check that the latest CI runs should be reasonably fresh (at least not older than a week?)

**Comment by apapirovski** [comment]
Could we include semver-minor in this? In general, more PRs should get CitGM runs than is currently the case. I've started running it for any change I make that touches internals in a significant way, even if it seems completely harmless. The CitGM job doesn't even take much longer to finish than the main CI.

**Comment by joyeecheung** [comment]
@apapirovski Well now come to think of it, maybe we should just create a label "citgm-needed"? The rule would be "semvor-major || citgm-needed".

I thought the reason why we don't run CITGM that often was because it's slow or we don't have enough resources (e.g. machines), but that might have changed or was never true... cc @nodejs/build @nodejs/citgm

**Comment by apapirovski** [comment]
FWIW the last successful CitGM job took 1hr16min within most results being available after the first 30-40 minutes.

**Comment by gibfahn** [comment]
>I thought the reason why we don't run CITGM that often was because it's slow or we don't have enough resources (e.g. machines), but that might have changed or was never true.

The biggest issue with CitGM is that it needs triage, modules fail all the time, usually unrelated to node core. There are also lots of modules with flaky tests. I don't think the runs have ever taken much more than an hour.

>On a side note, we should check that the latest CI runs should be reasonably fresh (at least not older than a week?)

A week seems reasonable to me, after that the runs get removed from Jenkins anyway, so aren't really trustworthy.
