### ISSUE TITLE
git-node-land: when `git am` fails, try again with `git am -3`

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#142]
Got a branch working locally but need to write some better hint messages before opening a PR..

**Comment by targos** [comment]
Why not always use the -3 option?

**Comment by joyeecheung** [comment]
@targos I am not sure either but that's what the [collaborator guide](https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md#technical-howto) suggests. Maybe a 3-way merge can go wrong more easily?
