### ISSUE TITLE
get-metadata: missing "Refs:" in metadata section

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#156]
For https://github.com/nodejs/node/pull/18310, "Refs:" was omitted in metadata section.

**Comment by cPhost** [comment]
@vsemozhetbyt can provide more details on this or do you have any clue why that happend?

**Comment by vsemozhetbyt** [comment]
@cPhost I cannot understand the cause.
Commit message:
```txt
doc: remove confusing signature in fs.md

Fixes: https://github.com/nodejs/node/issues/18305
Refs: https://github.com/nodejs/node/pull/13424
```
<details>
<summary>get-metadata output:</summary>

```console
$ winpty get-metadata.cmd 18310
√  Done loading data for nodejs/node/pull/18310
----------------------------------- PR info ------------------------------------
Title      doc: remove confusing signature in fs.md (#18310)
Author     Vse Mozhet Byt <vsemozhetbyt@gmail.com> (@vsemozhetbyt)
Branch     vsemozhetbyt:doc-fs-del-err-signature -> nodejs:master
Labels     doc, fast-track, fs
Commits    1
 - doc: remove confusing signature in fs.md
Committers 1
 - Vse Mozhet Byt <vsemozhetbyt@gmail.com>
------------------------------ Generated metadata ------------------------------
PR-URL: https://github.com/nodejs/node/pull/18310
Fixes: https://github.com/nodejs/node/issues/18305
Reviewed-By: Joyee Cheung <joyeec9h3@gmail.com>
Reviewed-By: Gireesh Punathil <gpunathi@in.ibm.com>
Reviewed-By: Richard Lau <riclau@uk.ibm.com>
--------------------------------------------------------------------------------
√  Requested Changes: 0
√  Approvals: 3, 1 from TSC (joyeecheung)
i  Last Full CI on 2018-01-23T03:47:53Z: https://ci.nodejs.org/job/node-test-pull-request-lite/115/
i  This PR is being fast-tracked
‼  This PR is closed
```
</details><br>
Seems to be a common case, [`REFS_RE`](https://github.com/nodejs/node-core-utils/blob/8e3d831dc5deee9b6e053f5a9f26b30b410cfaa0/lib/links.js#L5) is matched.

**Comment by cPhost** [comment]
Aren't you suppose to add `Refs: <url>` in for `get-metadata` it to detect it?

**Comment by gibfahn** [comment]
>Aren't you suppose to add Refs: <url> in for get-metadata it to detect it?

You can add it in the commit message or the first comment in the issue. Looks like @vsemozhetbyt added it to the commit message.

**Comment by cPhost** [comment]
Ah yeah, I don't know what i was thinking...

**Comment by cPhost** [comment]
@joyeecheung it looks this is failing because github is once again using `.issue-link` or something and the url is  not being parsed. 

I don't know why this did not came to my mind earlier but we can avoid using jsdom simply by using 
`bodyText` field rather than `bodyHTML` field.

**Comment by joyeecheung** [comment]
@cPhost I think the OP is about the URL in the commit message not being parsed, rather than the body of the PR?

**Comment by cPhost** [comment]
Yep, found that it, we need to also pass commit msg into `linkParser` and then get refs from one of them. I think

**Comment by joyeecheung** [comment]
@cPhost In that case it's not a bug caused by `.issue-link`, the jsdom parsing is there to work around text like `Refs: #XXXXX`. We should use something else for commit messages instead.

**Comment by cPhost** [comment]
@joyeecheung so we can just combine `bodyHTML` and `commitBodyHTML` and just passed to `LinkParse` should fix it.

**Comment by priyank-p** [comment]
I think this is no longer an issue since it didn't come up recently. 
And, my comments are all but un-understandable back then :(
