### ISSUE TITLE
get-metadata: missing 'LGTM' in comments

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#166]
PR: https://github.com/nodejs/node/pull/18630

Command: `winpty get-metadata.cmd 18630 --check-comments`

Output:
```console
------------------------------ Generated metadata ------------------------------
PR-URL: https://github.com/nodejs/node/pull/18630
Reviewed-By: Colin Ihrig <cjihrig@gmail.com>
Reviewed-By: Ruben Bridgewater <ruben@bridgewater.de>
--------------------------------------------------------------------------------
```

Missing: https://github.com/nodejs/node/pull/18630#issuecomment-363920740

**Comment by cPhost** [comment]
@vsemozhetbyt just want to confirm did the `get-metadata` output had something that said `maclover7 approved via LGTM in comment` or something along those lines? since this is all we do currently and it's not included in generated metadata.

**Comment by vsemozhetbyt** [comment]
@cPhost 
<details>
<summary>Full output:</summary>

```console
√  Done loading data for nodejs/node/pull/18630
----------------------------------- PR info ------------------------------------
Title      doc: fix link in https.md (#18630)
Author     Vse Mozhet Byt <vsemozhetbyt@gmail.com> (@vsemozhetbyt)
Branch     vsemozhetbyt:doc-fix-link-2018-02-07 -> nodejs:master
Labels     doc, fast-track, https, ready
Commits    1
 - doc: fix link in https.md
Committers 1
 - Vse Mozhet Byt <vsemozhetbyt@gmail.com>
------------------------------ Generated metadata ------------------------------
PR-URL: https://github.com/nodejs/node/pull/18630
Reviewed-By: Colin Ihrig <cjihrig@gmail.com>
Reviewed-By: Ruben Bridgewater <ruben@bridgewater.de>
--------------------------------------------------------------------------------
√  Requested Changes: 0
√  Approvals: 2, 1 from TSC (cjihrig)
i  Last Full CI on 2018-02-07T21:39:06Z: https://ci.nodejs.org/job/node-test-pull-request-lite/159/
i  This PR is being fast-tracked
‼  This PR is closed
```
</details><br>

**Comment by cPhost** [comment]
Ok thanks, this is a bug.

**Comment by joyeecheung** [comment]
I think we have already discussed about this. This is by design - only comments that contain nothing but LGTM will get a warning, other types of comments don't get anything at all, because there will always be  "something LGTM but I am not the expert in other things", and other types of thing that don't make them legitimate sign-offs.

**Comment by joyeecheung** [comment]
BTW in those cases, something like https://github.com/nodejs/node-core-utils/issues/140 would be more suitable because without NLP code, humans are better at deciding if a comment with "LGTM" is legitimate sign-off

**Comment by cPhost** [comment]
> I think we have already discussed about this. This is by design - only comments that contain nothing but LGTM will get a warning

Oh, okay it does make sense now, so this is not a bug. I glanced at the PR again quickly to get some idea all i got was we don't include in metadata which i already knew, and something that said `<name>(<username>) approved via LGTM in comment)` 😅.

**Comment by codebytere** [comment]
Gonna close this one since it's pretty old and i don't think this is something there's wide interest in doing but please reopen if that's not the case!
