### ISSUE TITLE
ncu-team: list organizations members

### ISSUE THREAD

**Issue by alopezsanchez** [nodejs/node-core-utils#169]
It may be useful to add the possibility to list organizations members instead of only team members.

What do you think?

**Comment by cPhost** [comment]
I don't think node core would need to list all of the members in node org. + if we think of fetching ~500 people i could take bit longer. 

That being said i'd like to hear what other have to say on this.

**Comment by tniessen** [comment]
I don't think this would benefit anyone, I am not even sure whether being a member of the org implies anything (?).

**Comment by joyeecheung** [comment]
Well...we do have the members team although not every member of the org is in it, but it's close.

**Comment by cPhost** [comment]
I think the question is answered so this could be closed? Please reopen if required.
