### ISSUE TITLE
git-node-land: lease?

### ISSUE THREAD

**Issue by srl295** [nodejs/node-core-utils#172]
Per the collaborator's guide, I end up with:
> `$ git push --force-with-lease srl295 master:icu-add-using`

this gives the little purple "merged" badge as per https://github.com/nodejs/node/pull/18667 thus not needing to close the PR yourself with "Landed in b8f47b27571f8d763f811f017be3fb37d466c4fc"

could/should the tool suggest this step?

**Comment by srl295** [comment]
I realized the tool doesn't `a priori` know which my branch is. But, it could find it from github metadata on the PR.

**Comment by codebytere** [comment]
Duplicate of https://github.com/nodejs/node-core-utils/issues/264
