### ISSUE TITLE
Set "main" field in package.json to a more sane value

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/node-core-utils#195]
In https://github.com/nodejs/node-core-utils/blob/master/package.json#L5, the "main" field has been set to a file that doesn't exist.

When this line was last edited, the working tree was very different (https://github.com/nodejs/node-core-utils/tree/ac457447c6b9c86f7698c784f69def68217f894a) and the value was valid, but it's not valid anymore. There are a few new files in the `bin` folder now and I cannot determine by myself which file should be placed there.

Let me know which one to add and I'd submit a patch.

If they're all equivalent, then perhaps we could add another file that prints out some sort of help text and call that instead.

**Comment by joyeecheung** [comment]
@ryzokuken Thanks for reporting....I think the `main` field and just be removed? There really isn't much to `require`, at least not for now..

**Comment by ryzokuken** [comment]
@joyeecheung Sure! I'll make a PR removing it prompty.

**Comment by ryzokuken** [comment]
@joyeecheung take a look at #196
