### ISSUE TITLE
Handle #issuecomment-371266836 like strings in PR link

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-core-utils#206]
Often when you're going through your notifications, you end up with something on the end of the pull request URL, for example:

```
https://github.com/nodejs/node/pull/19201#issuecomment-371266836
https://github.com/nodejs/node/pull/19201#event-1509291051
https://github.com/nodejs/node/pull/19201/files
https://github.com/nodejs/node/pull/19201#pullrequestreview-102067476
```

If you run `git node metadata https://github.com/nodejs/node/pull/19201#issuecomment-371266836` it just shows the help text.

It should be easy to adjust the regex to handle anything of the form

```bash
https://(?:www.)github.com/(\w\+)/(\w\+)/pull/([0-9]+).*
```

and just capture the three things you need (in `()`).

Also `https://www.github.com/nodejs/node/pull/19201` doesn't currently work.

**Comment by gibfahn** [comment]
IDK what the difference between `enhancement` and `feature request` is, so I'll ad both :grin:.

**Comment by cPhost** [comment]
> IDK what the difference between enhancement and feature request is, so I'll ad both 😁.

I added descriptions to some labels (including enhancements, and feature request), I might not be the best person to add those so maybe some else can add some descriptions :)

**Comment by gibfahn** [comment]
Just to add, it looks like you can't currently do `git node land https://github.com/nodejs/node/pull/19130`.

**Comment by cPhost** [comment]
> Just to add, it looks like you can't currently do git node land https://github.com/nodejs/node/pull/19130.

Can you open a new issue for this? I totally missed it.
