### ISSUE TITLE
Suggest updating config if upstream remote not found

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-core-utils#209]
Currently if you have an upstream remote not called `upstream`, and you choose to try to update from the remote branch, then `git-node` just errors out.

It should be possible to detect that the specified remote isn't defined in this directory, have the user choose their upstream name, and then run `ncu-config set upstream <chosen name>` for them before continuing.

```bash
? Do you want to try reset the branch to upstream/master? [Y/n] 
⠋ Bringing upstream/master up to date...fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by codebytere** [comment]
Resolved by https://github.com/nodejs/node-core-utils/pull/426
