### ISSUE TITLE
ncu-config updates wrong config file if $XDG_CONFIG_HOME set

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-core-utils#210]
`ncu-config set --global foo bar` should update `$XDG_CONFIG_HOME/ncurc` rather than `$XDG_CONFIG_HOME/.ncurc`.

```console
$ ls -A | grep ncurc
ncurc
$ cat ncurc
{
  "username": "gibfahn",
  "token": "<my token>"
}
$ ncu-config set --global upstream DANGER
Updating global configuration [upstream]: undefined -> DANGER
$ ls -A | grep ncurc
.ncurc
ncurc
$ cat .ncurc
{
  "upstream": "DANGER"
}% 
```

**Comment by cPhost** [comment]
@gibfahn this is due to the way you implemented `$XDG_CONFIG_HOME/ncurc` in #136.

Questions should `$XDG_CONFIG_HOME/ncurc` be made consistent with `.ncurc` and add `.` to it, or just fix the function in `config.js`?

**Comment by gibfahn** [comment]
>Questions should $XDG_CONFIG_HOME/ncurc be made consistent with .ncurc and add . to it, or just fix the function in config.js?

I'd vote for the latter. Using non-hidden files in `$XDG_CONFIG_HOME` is the standard thing to do.

Also currently I think the logic here:

https://github.com/nodejs/node-core-utils/blob/8184d92f69b5713e6cce94fd13fe7eb8f9434f39/lib/config.js#L19-L22

duplicates the logic here:

https://github.com/nodejs/node-core-utils/blob/8184d92f69b5713e6cce94fd13fe7eb8f9434f39/lib/auth.js#L22-L29

So I'd have thought the easiest thing to do would be to have one function that gets the global config file location, and have both places call it.

**Comment by cPhost** [comment]
ok, cool the issue will be fixed by making it hidden. We can later do a pass for refactoring.

**Comment by gibfahn** [comment]
>ok, cool the issue will be fixed by making ncurc it hidden. We can later do a pass for refactoring.

Just to be super-clear (I wasn't in my previous comment), I do not think we should change the path to `$XDG_CONFIG_HOME/.ncurc`, we should keep it as `$XDG_CONFIG_HOME/ncurc` and use that in `config.js` as well.

**Comment by cPhost** [comment]
Oh, okay that is what I wanted to know.
