### ISSUE TITLE
get-metadata outputs errors it shouldn't due to "exit no-zero on failure" feature

### ISSUE THREAD

**Issue by cPhost** [nodejs/node-core-utils#212]
It looks because of PR #199, we output errors that should be logged out in case PR checks fails.

<details>
<summary><code>git node metadata 19201</code></summary>
<pre><code>
✔  Done loading data for nodejs/node/pull/19201
----------------------------------- PR info ------------------------------------
Title      deps: update V8 to 6.6 (#19201)
Author     Michaël Zasso <targos@protonmail.com> (@targos)
Branch     targos:v8-6.6 -> nodejs:master
Labels     V8 Engine, blocked, semver-major
Commits    9
 - deps: update V8 to 6.6.346.6
 - build: reset embedder string to "-node.0"
 - src: update NODE_MODULE_VERSION to 63
 - build: update node.gyp to reference gypfiles/v8.gyp
 - deps: update v8.gyp
 - test: remove test for shared array buffers transfer
 - test: fix promise message test after V8 update
 - util: add type check functions for BigInt arrays
 - fixup: add bigint arrays in test
Committers 1
 - Michaël Zasso <targos@protonmail.com>
------------------------------ Generated metadata ------------------------------
PR-URL: https://github.com/nodejs/node/pull/19201
Reviewed-By: Ali Ijaz Sheikh <ofrobots@google.com>
Reviewed-By: Myles Borins <myles.borins@gmail.com>
Reviewed-By: Matteo Collina <matteo.collina@gmail.com>
Reviewed-By: Colin Ihrig <cjihrig@gmail.com>
--------------------------------------------------------------------------------
✔  Requested Changes: 0
✔  Approvals: 4, 4 from TSC (ofrobots, MylesBorins, mcollina, cjihrig)
ℹ  Last Full CI on 2018-03-07T16:33:39Z: https://ci.nodejs.org/job/node-test-pull-request/13568/
ℹ  Last V8 CI on 2018-03-07T16:33:39Z: https://ci.nodejs.org/job/node-test-commit-v8-linux/1254/
⚠  Commits were pushed after the last Full CI run:
⚠  - fixup: add bigint arrays in test
ℹ  This PR was created on Wed Mar 07 2018 (weekday in UTC)
⚠  1 hours left to land
✖ Getting commits from nodejs/node/pull/19201
✖  PR checks failed
Error: PR checks failed
    at getMetadata.then (/home/ubuntu/workspace/node-core-utils/components/git/metadata.js:89:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
git-node metadata <identifier>

Retrieves metadata for a PR and validates them against nodejs/node PR rules

Positionals:
  identifier  ID or URL of the pull request                            [string] [required]

Options:
  --version         Show version number                                          [boolean]
  --help            Show help                                                    [boolean]
  --owner, -o       GitHub owner of the PR repository         [string] [default: "nodejs"]
  --repo, -r        GitHub repository of the PR                 [string] [default: "node"]
  --file, -f        File to write the metadata in                                 [string]
  --readme          Path to file that contains collaborator contacts              [string]
  --check-comments  Check for 'LGTM' in comments                                 [boolean]
  --max-commits     Number of commits to warn                        [number] [default: 3]

Examples:
  git node metadata 12344                        Retrieve the metadata of
                                                 https://github.com/<nodejs>/<node>/pull/12344
                                                 and validate the PR
  git node metadata                              Retrieve the metadata of
  https://github.com/<nodejs>/<node>/pull/12344      https://github.com/nodejs/node/pull/12344
                                                 and validate it
  git node metadata 167 --repo llnode --readme   Retrieve the metadata of
  ../node/README.md                              https://github.com/<nodejs>/<llnode>/pull/167
                                                 and validate it using the README in
                                                 ../node/README.md

TypeError: Cannot read property 'replace' of undefined
    at CLI.error (/home/ubuntu/workspace/node-core-utils/lib/cli.js:130:52)
    at getMetadata.then.catch (/home/ubuntu/workspace/node-core-utils/components/git/metadata.js:96:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
</code></pre>
</details>

**Comment by GithubGoldMiner** [comment]
Hi @cPhost @joyeecheung , I have a quick question here (I apologize if this is a silly question). In your log when you run `git node metadata 19201`, is it suppose to print out the trace like this:
```
Error: PR checks failed
    at getMetadata.then (/home/ubuntu/workspace/node-core-utils/components/git/metadata.js:89:15)
    at 
    at process._tickCallback (internal/process/next_tick.js:160:7)
```
Is this a feature or an issue?

For the `TypeError` you got after you run `git-node metadata`, it seems that it is not reproducible on my end. Do you have any insight about it?

Thank you for answering my questions.
