### ISSUE TITLE
"No full CI runs" warning

### ISSUE THREAD

**Issue by vsemozhetbyt** [nodejs/node-core-utils#225]
Not sure if this is intended, but since the last update this warning appears even for PR warrantable for CI-lite:
https://github.com/nodejs/node/pull/19721
```console
√  Requested Changes: 0
√  Approvals: 3, 1 from TSC (cjihrig)
×  No full CI runs detected
i  Last Lite CI on 2018-04-01T07:36:06Z: https://ci.nodejs.org/job/node-test-pull-request-lite/375/
‼  This PR is being fast-tracked, but awating a CI run
```

**Comment by cPhost** [comment]
Here is the code that we need to fix, need to add Lite category in the check as well:

https://github.com/nodejs/node-core-utils/blob/8c6f7cc7e30f98fa0322a20c29ce83548650b9d9/lib/pr_checker.js#L206-L209

I think it's okay to add LITE category as trusted and not change the status right?

**Comment by joyeecheung** [comment]
> I think it's okay to add LITE category as trusted and not change the status right?

SGTM
