### ISSUE TITLE
remove eu-strip from node tarball

### ISSUE THREAD

**Issue by jvelezpo** [nodejs/node-core-utils#245]
nodejs 10.0.0 tarball contains `deps/v8/third_party/eu-strip/`
and it was removed on this PR https://github.com/nodejs/node/pull/20304

now we need  to stop it coming back the next time V8 is updated. I have been trying to do this but i havent been able to do it, if anyone can help me figure it out how to do it, or if anyone wants to send a PR it will be awesome as well.

**Comment by priyankp10** [comment]
@jvelezpo this is already implemented in #243, so if you use `git node v8` to update this should be taken care of next time.

**Comment by priyankp10** [comment]
Closing issue, since it's something already done.

**Comment by jvelezpo** [comment]
@priyankp10 thanks
