### ISSUE TITLE
git-node: `git node open` to create a new PR/open existing PR

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#252]
Basically what `git cl upload` and `git cl web` does for chromium/v8, but in one command.

Rough sketch:

1. Make sure the user is not on master, proposal, release or staging branches
2. Create a remote branch in the users' fork (might need to `ncu-config` that remote) if there isn't one
3. Push to that remote branch (note that this results in an actual push, we may not want to do that in ncu and only want to prompt the user do that before running `git node open --continue`)
4. Open the PR creation URL in the browser, and ask the user to come back to the terminal to fill in the PR id when they finished summiting the PR
5. Store the association locally in `.ncu`
6. When the user run `git node open` again, open the PR in the browser
7. Bonus: when the user run `git node land` from the PR, switch to the master branch, land the PR, prompt the user to push to the remote PR branch first to make the PR status "merged" (purple) before pushing to master

If we are feeling adventurous...

- In step 4, prompt the user to input the PR message (like what `git cl upload` does) and create the PR for the user. When the PR is created, do step 5, ask if the user wants to trigger the CI and if they do, trigger a CI, post the CI link in the PR (fancy: do a dropdown list from the CLI, let them choose jobs like the benchmark, citgm, etc.)

**Comment by devsnek** [comment]
maybe `git node pr open` just for ambiguity?

**Comment by joyeecheung** [comment]
@devsnek Good idea. We can add `git node pr set <url>` or `git node pr get` that basically does what `git cl issue` does.

**Comment by joyeecheung** [comment]
We should also consider https://github.com/nodejs/node-core-utils/issues/194 to make sure the commands are somewhat intuitive.

**Comment by joyeecheung** [comment]
About triggering the CI: maybe it's better if we split that into a separate command
