### ISSUE TITLE
git-node: count jenkins pipeline and/or Travis as effective CI runs

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#259]
Refs: https://github.com/nodejs/github-bot/pull/178 that runs the jenkins pipeline for collaborator PRs. The bot currently comments on the PR with a link to the job after the build is started.
Refs: https://github.com/nodejs/node/pull/21059 which runs the Travis CI for non-collabortor PRs. The existence of the job can only be tracked in the Github status API or via Travis API.

Both of them only serve the same purpose as the original Lite CI. For non-doc-only PRs we still require a full CI triggered by human (for now at least).

One way to fix this easily is, instead of only looking at the thread for CI links, also look at the status API to find jobs run for the last effective commit of the PR.
(Personally, I would want a warning to remind people to post the link to the PR because when the PR is landed, no one will ever know about those links if they only exist in the status API. I think someone raised concern about that before)

**Comment by joyeecheung** [comment]
This is how the pipeline link looks: https://github.com/nodejs/node/pull/21430#issuecomment-398910078

**Comment by vsemozhetbyt** [comment]
CI-lite detection is also broken now. Refs: https://github.com/nodejs/node/pull/21938
