### ISSUE TITLE
Wrong state after fixing `git am` conflict

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#277]
I was trying to land https://github.com/nodejs/node/pull/21992 which had a small conflict to fix.

So I ran:
```bash
git node land 21992
# stopped at `git am`. fix conflict
git add .
git am --continue
git node land --continue
```

At this point, it tries to re-download and apply the patch.

**Comment by joyeecheung** [comment]
Are you using master or the npm release? It may be fixed by https://github.com/nodejs/node-core-utils/commit/34664c0a1ac4f5930b804a1bf9960585f2a74e99

**Comment by targos** [comment]
The npm release. I didn't realize it was so for behind, sorry.

**Comment by joyeecheung** [comment]
No worries, I'll publish a new release

**Comment by targos** [comment]
Thank you! Since it's not common to land PRs which still have conflicts, I'll close this as likely fixed.
