### ISSUE TITLE
doc: clarify how to set up local config before using git-node

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#291]
I got reminded that this example in https://github.com/nodejs/node-core-utils/blob/master/docs/git-node.md#prerequistes:

```
$ cd path/to/node/project
$ ncu-config set upstream your-remote-name
$ ncu-config set branch your-branch-name
```

is not clear enough and it wasted time for a few collaborators to figure out that the last argument (`value`) should be a name of the git remote, and `upstream` is the key name.

(Also probably only me will see it but if anyone is confused by the docs again, please send a PR or tell me!)

**Comment by joyeecheung** [comment]
One way to clarify:

```
$ git remote add upstream git@github.com:nodejs/node.git # add a remote called "upstream"
$ git remote -v

upstream	git@github.com:nodejs/node.git (fetch)
upstream	git@github.com:nodejs/node.git (push)

$ ncu-config set upstream upstream # tell ncu that your upstream is named "upstream"
$ ncu-config set branch master # tell ncu that you are landing patches to "master"
````

**Comment by targos** [comment]
I wondered a few times why we actually need to configure this. Can't we use the current branch and get the upstream name from the local git config?

**Comment by codebytere** [comment]
Closed by https://github.com/nodejs/node-core-utils/pull/292
