### ISSUE TITLE
Not sure what `git node land --final` is supposed to do

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-core-utils#293]
I just landed a PR with `git node land`, then did what it said (push to upstream, and add "Landed in ..." comment).

Then reading the docs I saw there was a `--final`. I called it to see what it does, but it doesn't want to do anything, and has a misleading warning message:

```
core.linux/node (master $ u=) % git node land --abort
✔  No git am in progress
✔  No git rebase in progress
```

No am in progress, but right after I see:

```
core.linux/node (master $ u=) % git node land --final
⚠  Not yet ready to final
A git rebase/am is in progress. Please complete it before running git node land --final
```

Whatever is triggering that warning seems to be confused.

And I still don't know what `--final` does :-). I suspect it might have to do with some kind of longer session, perhaps with multiple commits,  a situation I haven't seen yet.

**Comment by joyeecheung** [comment]
I am not sure what to do from here...would checking if the commit has already been pushed to the upstream before printing

> git rebase/am is in progress. Please complete it before running git node land --final

help? I guess in that case we could just go ahead and finish the cleanup.

> And I still don't know what --final does :-). I suspect it might have to do with some kind of longer session, perhaps with multiple commits, a situation I haven't seen yet.

That's what it's for, yes. `--final` basically just validates the commit messages for commit(s) that are not in the upstream yet, and clean up the temporary files if necessary. Code is in https://github.com/nodejs/node-core-utils/blob/c48050a0beb8cae7bcd502a7e406903117144373/lib/landing_session.js#L200-L239
