### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by jasnell** [nodejs/node-core-utils#3]
*fantastic work on this* ... loving it.

A couple wish list items that I will *try* to get to but would love if others get to it first:

* [x] An informational listing of the labels applied to the PR
* [x] Printing the PR title
* [x] Printing the number of individual commits in the PR (useful to know if squashing may be necessary)
* [x] If any commits use `[Squash]` in their title line, a nice warning saying that Squashing is required
* [x] Print the PR target branch, along with a warning if running `get-metadata` from within the node source tree and the current git branch does not match the target branch... to help defend against accidentally landing something in the wrong branch. 
* [ ] Warning for "Dont Land on ..." labels

**Comment by joyeecheung** [comment]
On a side note: at this point I think we should rename the binary from `get-metadata` to something else XD it already does a lot more than generating metadata now..

**Comment by cPhost** [comment]
@joyeecheung we should use sync.io as we are using npm packages it will warn us about suspicious packages.

**Comment by cPhost** [comment]
@joyeecheung about renaming binary `get-metadata`. I have some suggestion.
`get-pr`
`get-meta`

we should probably make it a command binded to package `node-core-utils`.
`node-utils get-pr`
`nodejs-automation get-pr | get-meta | get-metadata`

**Comment by joyeecheung** [comment]
@cPhost Actually I kind of prefer `get-metadata` now that I have used it a few times...because you would usually just want to check things & generate metadata, there aren't really much use cases where you wound want to separate those.

**Comment by joyeecheung** [comment]
@cPhost Giving it a bit of thought I think making a larger target like `land-pr` in https://github.com/joyeecheung/node-core-utils/issues/10 would make more sense, in that case it's OK to use potentially outdated metadata because

A) This is likely what we are going to do in a complete landing session in practice anyway, last-moment reviews could get omitted if the user does not keep an eye on the browser tab
B) This is closer to the semantics of `git cherry-pick`, which is used to land PRs

**Comment by cPhost** [comment]
@joyeecheung That sounds good to me.

**Comment by joyeecheung** [comment]
@cPhost I do love the idea of piping things tho because I write small bash commands using pipes all the time, it would be great if we can think of some good formats of output that can interact well with other utilities..

**Comment by joyeecheung** [comment]
I've crossed out the first two items because those should be fixed by https://github.com/joyeecheung/node-core-utils/pull/57

**Comment by apapirovski** [comment]
Third is also taken care of by it :)

**Comment by joyeecheung** [comment]
I think most items are implemented other than:

> Warning for "Dont Land on ..." labels

We do not warn on `[Squash]` but prompt to run `--autosquash` if an autosquashable commit (with `fixup!` or `squash!`) is present.
