### ISSUE TITLE
FR: check CI job result

### ISSUE THREAD

**Issue by refack** [nodejs/node-core-utils#308]
I was about to suggest that if the PR is labeled `V8 Engine` we should check for a V8 CI job, but I just saw that we already do 😄 :
```
i  Last V8 CI on 2018-11-10T22:17:13Z: https://ci.nodejs.org/job/node-test-commit-v8-linux/1838/
i  Last Lite PR Pipeline CI on 2018-11-14T17:57:34Z: https://ci.nodejs.org/job/node-test-pull-request-lite-pipeline/1615/
```

So how about we query Jenkins for it's status?

**Comment by joyeecheung** [comment]
So..the code for querying Jenkins and parsing the results are already part of ncu-ci, I guess we just need some glue to invoke them from git-node..

**Comment by refack** [comment]
I'll try to draft something this weekend.

**Comment by mmarchini** [comment]
Implemented on https://github.com/nodejs/node-core-utils/pull/422
