### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#309]
Can we have a new release on npm?

I would like the new things in `git-node v8` command to be available :)

@joyeecheung

**Comment by refack** [comment]
What? You don't run off the git clone 😉

**Comment by targos** [comment]
"do what you gotta do" :)

**Comment by joyeecheung** [comment]
@targos Done. Do you want npm collaborator access?

**Comment by targos** [comment]
@joyeecheung 
> Do you want npm collaborator access?

I'd be glad to have it, thanks

**Comment by joyeecheung** [comment]
I've added @targos to the npm collaborators.
