### ISSUE TITLE
Ammended commit message, then got lost

### ISSUE THREAD

**Issue by rvagg** [nodejs/node-core-utils#317]
So I did a `git node land` and got to a point where I needed to edit the commit message (I had `Ref:` lines in there already but it had found and inserted the same lines so I had two of all of them). It dropped me out and gave me the instructions about editing a file and `git am` to get it in .. but then what? It didn't tell me anything beyond this. I'm new to this tool and have since found `-c`, but at first I was taking guesses like: is this a subshell that I'm supposed to exit? (nope, exited and lost my history so can't screenshot or quote anything now).

So I guess more instructions at this point in the process might be good.

**Comment by priyank-p** [comment]
I am not entirely sure but reading the [git-node docs](https://github.com/nodejs/node-core-utils/blob/master/docs/git-node.md) and specifically the [demo section](https://github.com/nodejs/node-core-utils/blob/master/docs/git-node.md#demo--usage) in the docs should help you out.

**Comment by joyeecheung** [comment]
Usually I will just `git node land --continue` and it will know what to do.

I think https://github.com/nodejs/node-core-utils/pull/285 would improve this but it's somewhat stalled
