### ISSUE TITLE
git-node: detect CI status also from the GitHub API

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#324]
Currently it only parses the thread and looks for CI links pasted manually, but it can also just query the GitHub API for the status of the last commit in the PR in case someone forgets to paste the link.

We cannot replace the link parsing entirely with this though because the github bot does not always update the CI status reliably. If the node-test-commit status of the last commit is not green we could also print a warning (again we cannot just error because the bot or Jenkins is not always reliable)

**Comment by sam-github** [comment]
I think @richardlau made a good point in https://github.com/nodejs/node/pull/25861#issuecomment-461256551 that having `ci: ` is good for after the fact observation.

The suggestion I would make for `git node land` is that when it says no CI detected, it mention specifically that it is looking for a `ci:` comment. You could print a message saying "ci passed, but not comment, please add `ci: ...` as a comment.... but honestly, just clarity about what the tool is looking for would be enough, IMO.

**Comment by joyeecheung** [comment]
@sam-github That's a good point. Although it would still be useful to query the CI status and display a hint if it's not green or yellow, so that the user is aware that they are pushing a commit to master that did not fully pass the CI (even when it's just flaked).
