### ISSUE TITLE
git-node: err in CI date math

### ISSUE THREAD

**Issue by srl295** [nodejs/node-core-utils#338]
node-core-utils@1.16.1

My PR: https://github.com/nodejs/node/pull/27370

```
   ℹ  Last Lite PR Pipeline CI on 2019-04-23T17:04:57Z: https://ci.nodejs.org/job/node-test-pull-request-lite-pipeline/3341
   ℹ  Last Full PR CI on 2019-04-24T22:27:33Z: https://ci.nodejs.org/job/node-test-pull-request/22696/
```

but I kept getting: 
> ⚠ Commits were pushed after the last Lite PR Pipeline CI run:

debugging i see:

>    { committedDate: '2019-04-24T21:44:09Z'
> a461aa39d098930d668298480cd415569e92f53a

>   lastCI:
>   { typeName: 'Lite PR Pipeline', date: '2019-04-23T17:04:57Z' } }

so the 'lastCI' is the lite one on the 23rd, not the full on the 24th  1 hour after the fact.

===Found it===

I think this is the bug, `pr_checker.js:199`

```js
       if (!lastCI || lastCI.date > ci.date) {
```

this will only replace a CI if it is *newer* we have

```js
       if (!lastCI || lastCI.date < ci.date) {
```

**Comment by richardlau** [comment]
This was fixed in https://github.com/nodejs/node-core-utils/pull/334 but we haven't had a release containing it.

**Comment by srl295** [comment]
oops dup of #334

**Comment by srl295** [comment]
duplicate comment also..
