### ISSUE TITLE
git node land --continue should detect rebase

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#341]
During a `git node land` session, I had to rebase a fixup commit.

My session went like this:
```
git node land 27415
git rebase upstream/master -i -x "git node land --amend" --autosquash
vim /home/mzasso/git/nodejs/node/.ncu/27415/7359e03-message
git commit --amend -F /home/mzasso/git/nodejs/node/.ncu/27415/7359e03-message
git node land --continue
git show
git push upstream master
```

You can see that I forgot to do `git rebase --continue` and ended up pushing my master branch in its state before the rebase.
I think `git node land --continue` should be able to detect that a rebase is in progress and stop whith a recommendation.

**Comment by joyeecheung** [comment]
Hmm, we do have this logic

https://github.com/nodejs/node-core-utils/blob/08dd8f80f72858c0733212a9db26fabc176ecba0/lib/landing_session.js#L186-L190

Somehow it was not effective.
