### ISSUE TITLE
git land stuck on windows

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-core-utils#358]
The second prompt (sorry for not keeping the message) after type `Y`, the command stucked, both in cmd and git-bash.

Env info
``` 
 System:
    OS: Windows 10 1903
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 7.14 GB / 15.89 GB
  Binaries:
    Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
```

cc @gireeshpunathil @mcollina

**Comment by gireeshpunathil** [comment]
I cant reproduce this, but I saw it for sure in the remote screen of @gengjiawen when we were onboarding him. :)

**Comment by richardlau** [comment]
Could it be related to https://github.com/nodejs/node-core-utils/issues/358 (something prompting for input)?

**Comment by joyeecheung** [comment]
I think it may be related to https://github.com/nodejs/node-core-utils/issues/356

**Comment by gengjiawen** [comment]
> I think it may be related to #356 - there is a prompt from git and we are not handling it correctly.

My ssh key has no password, is it still the case ? Also can I change some file to show the extra info so I can get more info in my case.

**Comment by joyeecheung** [comment]
@gengjiawen there are other cases where git may prompt and wait for an answer e.g. the upstream server you are creating an ssh connection to is unknown. It's possible that write like this:

https://github.com/nodejs/node-core-utils/blob/f3f59dad963cc67924ed02aef3f6a2f7a0550479/lib/session.js#L295

covers the prompt from git. The fix would be to pay attention to commands like this that send a prompt, don't wrap it with spinners, and pipe the stdin into it when necessary.
