### ISSUE TITLE
v8 backport hangs at "Apply patch"

### ISSUE THREAD

**Issue by devsnek** [nodejs/node-core-utils#359]
it's just been twirling here for the past five minutes

![](https://gc.gy/29522799.png)

**Comment by targos** [comment]
It's not easy to see but under "Apply patch", there are instructions.
This happens when there is a conflict. What you need to do is keep this terminal as it is, fix the conflict and then come back to the terminal, type `resolved` and press "Enter".

**Comment by devsnek** [comment]
oh i see. the way i read this screen was that "Resolve merge conflicts and enter RESOLVED" was going to be the next step, not the current step.

**Comment by joyeecheung** [comment]
I guess this can be closed now. Feel free to reopen if there are more actions to be done.
