### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by richardlau** [nodejs/node-core-utils#370]
The last release was back in May. Since then fixes have gone in, e.g. https://github.com/nodejs/node-core-utils/pull/354, for issues which I think users are running into: https://github.com/nodejs/node/issues/29770#issuecomment-536652488

**Comment by sam-github** [comment]
https://www.npmjs.com/package/node-core-utils --- looks like only @joyeecheung and " nodefoundation" can publish it?

**Comment by joyeecheung** [comment]
Done https://github.com/nodejs/node-core-utils/releases/tag/v1.18.0

Anyone wants to help keeping it published on npm?

cc @targos since he maintains git-v8

**Comment by targos** [comment]
I don't mind having publish rights on npm

**Comment by joyeecheung** [comment]
@targos Are you also targos on npm? (just to be extra safe)

**Comment by targos** [comment]
> @targos Are you also targos on npm? (just to be extra safe)

Yes I am

**Comment by trivikr** [comment]
I believe this issue can be resolved as:
* the new release was done with [v1.18.0](https://github.com/nodejs/node-core-utils/releases/tag/v1.18.0)
* @targos was given publish rights, and release [v1.18.1](https://github.com/nodejs/node-core-utils/releases/tag/v1.18.1)
