### ISSUE TITLE
add travis build checks to git-node-land

### ISSUE THREAD

**Issue by sam-github** [nodejs/node-core-utils#375]
https://github.com/nodejs/node-core-utils/pull/369 is a round-about way of doing it, but apparently not reliable (https://github.com/nodejs/node-core-utils/pull/369#issuecomment-548953916). If it was reliable, then all the specific code to check Jenkins or Travis would be unnecessary, so  that's unfortunate.

Note that since https://github.com/nodejs/node/pull/30330 only Travis has been required for doc-only tests.

There have also been musings (some by me) of using Travis more for actual CI testing:
- https://github.com/nodejs/build/issues/1593#issuecomment-554485910
- https://github.com/nodejs/build/issues/2016#issuecomment-548858369

This would require Travis failures to block landing PRs.

**Comment by codebytere** [comment]
Closing as Node.js PRs now use Jenkins and GitHub actions, checks for both of which are included in `git-node-land` logic :)
