### ISSUE TITLE
Don't use `--whitespace=fix` for changes on `deps/`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-core-utils#400]
Not sure if there's an easy way to do it, but we had recent CI failures on master and v12 because --whitespace=fix made invalid changed to V8 test fixtures. Since we sync `deps/` from upstream projects, avoiding unwanted whitespace changes there is probably a good idea.

**Comment by targos** [comment]
I wonder if we shouldn't just remove the flag altogether. There are also some `tools` where we probably shouldn't apply it and for the rest, code review can spot the rare case where people introduce extra whitespaces.

**Comment by codebytere** [comment]
I think i'd be in favor of removing it altogether as well - happy to take this if that's the direction we wanna go!
