### ISSUE TITLE
git-node release: issues with changelog generation

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#404]
Notes I took while I was preparing the proposal for v13.13.0.

- `getChangelog()` doesn't work if the user isn't authenticated.
  - It returns the string `"Your GitHub username:"`
- After manual authentication, `getChangelog()` triggers an abuse detection mechanism:
  - `Error fetching issue #30436: Error from GitHub: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.`
- On another machine, the process runs out of memory while the `updateMajorChangelog` method is running.

**Comment by codebytere** [comment]
@targos those are both unfortunately long-running hazards of `branch-diff` from what i recall, which is invoked in `getChangelog()`... can you replicate it there? I can at the very least attempt to add some error guarding around that should it fail 🤔

**Comment by targos** [comment]
I can replicate with: `npx changelog-maker --group --filter-release --start-ref v13.12.0`
It's weird, because on my Windows machine, it triggers the abuse detection, but on my Linux it doesn't.

**Comment by codebytere** [comment]
@targos one thing i've been considering is a small refactor of `changelog-maker` that batched requests to help prevent false-positive abuse detection errors, but i haven't had the time - i can try to stab at that upcoming maybe!
