### ISSUE TITLE
Update deprecated github APIs

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#406]
I just used node-core-utils on a new device and set up the connection to github and it seems like we are using a deprecated API:

```
Hi @BridgeAR,

On April 23rd, 2020 at 22:10 (UTC) you or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent Magic Node.js application that does magic things with ghauth.

We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow

You can learn more about these changes by visiting our developer blog https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

Thanks,
The GitHub Team
```

**Comment by codebytere** [comment]
i'm happy to take this one! pretty sure i know the small refactor we need to make.

**Comment by codebytere** [comment]
It's actually an issue with [`ghauth`](https://github.com/rvagg/ghauth/blob/master/ghauth.js#L12) though - we might want to fix it there although it's also feasibly fixable here if we potentially want to remove use of that module 🤔

**Comment by BridgeAR** [comment]
I have no strong opinion either way.

**Comment by aduh95** [comment]
I believe the upstream issue has been fixed. Closing, please reopen if I missed something.
