### ISSUE TITLE
feature request: system proxy support 

### ISSUE THREAD

**Issue by Himself65** [nodejs/node-core-utils#407]
My PC have to use proxy to access GitHub (you know why)

```bash
git node --proxy $URL land $PR
# or
git node set proxy="$URL" # set proxy to config
# or
git node --proxy land $PR # use proxy in config
```

and I will take some time to handle this

**Comment by targos** [comment]
I think if we support `git node set proxy`, the configured proxy should then be used automatically, not with an explicit `--proxy` flag in the commands.

**Comment by Himself65** [comment]
sure, and use proxy config in global `.gitconfig` is also ok. Just need a way to use proxy whatever it is :|

```gitconfig
# in .gitignore
[https]
	proxy = http://127.0.0.1:7890
[http]
	proxy = http://127.0.0.1:7890
```

**Comment by targos** [comment]
another way to provide proxy that I have seen is to use the `http_proxy` and `https_proxy` environment variables.

**Comment by Himself65** [comment]
I don't think it has any effect... :(
![image](https://user-images.githubusercontent.com/14026360/80356732-75c7c400-88ac-11ea-9ccf-d051dea87bd3.png)

**Comment by targos** [comment]
No, but I mean that we could support that or use a library that does

**Comment by joyeecheung** [comment]
We use node-fetch for git-node-land (not sure about other commands) so at least it should be fairly doable by using with one of the proxy agent implementations on npm with https://github.com/node-fetch/node-fetch#custom-agent But be aware that we need to configure the proxy setting for the git repository so that git picks it up and that may be tricky, especially for people who use SSH instead of HTTPS (then the setting needs to go to the SSH config, which is global), to make git-node support all of them, we may have the change the setting of the entire system.

**Comment by Himself65** [comment]
I code a simple implementation for self-use, later I will finish the PR

```diff
diff --git a/lib/request.js b/lib/request.js
index 3aff3e9..d5cccb5 100644
--- a/lib/request.js
+++ b/lib/request.js
@@ -1,13 +1,15 @@
 'use strict';

 const fetch = require('node-fetch');
+const HttpsProxyAgent = require('https-proxy-agent');
 const fs = require('fs');
 const path = require('path');
 const { CI_DOMAIN } = require('./ci/ci_type_parser');

 class Request {
-  constructor(credentials) {
+  constructor(credentials, proxyUrl) {
     this.credentials = credentials;
+    this.proxyAgent = new HttpsProxyAgent('http://127.0.0.1:7890');
   }

   loadQuery(file) {
@@ -16,6 +18,7 @@ class Request {
   }

   async text(url, options = {}) {
+    options.agent = this.proxyAgent;
     if (url.startsWith(`https://${CI_DOMAIN}`)) {
       options.headers = options.headers || {};
       Object.assign(options.headers, this.getJenkinsHeaders());
@@ -24,6 +27,7 @@ class Request {
   }

   async json(url, options = {}) {
+    options.agent = this.proxyAgent;
     options.headers = options.headers || {};
     options.headers.Accept = 'application/json';
     if (url.startsWith(`https://${CI_DOMAIN}`)) {
@@ -65,6 +69,7 @@ class Request {
     }
     const url = 'https://api.github.com/graphql';
     const options = {
+      agent: this.proxyAgent,
       method: 'POST',
       headers: {
         Authorization: `Basic ${githubCredentials}`,
```
