### ISSUE TITLE
`git node backport v8` does not work on macOS

### ISSUE THREAD

**Issue by dominykas** [nodejs/node-core-utils#421]
I got an error saying `Resolve merge conflicts and enter 'RESOLVED'` - however there were no conflicts. The actual underlying failure was `patch: unrecognized option '--merge'` - it seems the `patch` on macOS does not have that option.

I'm happy to research/PR whatever would be considered an acceptable fix?

Also not sure if there's a good way to detect conflicts vs other kinds of errors - the error message was rather misleading.

**Comment by codebytere** [comment]
The line originates [here](https://github.com/nodejs/node-core-utils/blob/a9c0676d0f64df5c8e86d7287f69381dc64049f2/lib/update-v8/backport.js#L203-L210) and unfortunately it looks like you're right - the patch commands are similar on macOS and on Linux but there are some nontrivial option differences, one of which is the `--merge` command.

I think our best bet here is probably to move away from the `patch` command and use `git apply` to accomplish the same goal. The consequent difference unfortunately though is that `git apply` won't apply patch if you have other uncommitted changes in your code, & it also won't apply a patch that does not apply cleanly. The above linked code would therefore require some light restructuring to take those externalities into account.

cc @targos for other thoughts!

**Comment by dominykas** [comment]
I don't know what `patch --merge` leaves on the filesystem when there's a conflict, but `git apply -3` (to do a three-way merge) worked for me 👍

**Comment by targos** [comment]
@dominykas what did `git apply -3` leave?

**Comment by dominykas** [comment]
@targos the `<<<<<<< ours` delimited stuff - not sure what it's called.

**Comment by targos** [comment]
I vaguely remember that `git apply` didn't always leave conflict markers, but maybe I'm wrong. And it's probably better to have something that work sometimes on all platforms than never on macOS
