### ISSUE TITLE
Changing commit messages should be improved

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#424]
Right now when changing the commit messages a file is added and that has to be changed. This is not really straight forward:

```
? Use this message? No
Please manually edit /home/ruben/repos/node/node/.ncu/33405/8e7685a4d15a-message, then run
`git commit --amend -F /home/ruben/repos/node/node/.ncu/33405/8e7685a4d15a-message` to finish amending the message
```

It would be easier to apply the metadata right away and to let the user then change the commit message with `git commit --amend`. That would be more straight forward and easier to handle for people landing PRs.

**Comment by joyeecheung** [comment]
It should be good to add a question here about copying it and use `clipboardy.writeSync` to copy it.

**Comment by aduh95** [comment]
Resolved by https://github.com/nodejs/node-core-utils/commit/811de87206806246a98033c60c5db2557d56da12. Closing, please reopen if I'm mistaken.
