### ISSUE TITLE
ncu-ci pr failed

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-core-utils#452]
On latest commit for PR: https://github.com/nodejs/node/pull/34086#issuecomment-650573553
```console
ncu-ci pr 34086
--------------------------------------------------------------------------------
[1/1] Running PR: 34086
--------------------------------------------------------------------------------
✔  Build data downloaded
TypeError: Cannot read property 'find' of undefined
    at PRBuild.setBuildData (/usr/local/lib/node_modules/node-core-utils/lib/ci/ci_result_parser.js:208:28)
    at PRBuild.getResults (/usr/local/lib/node_modules/node-core-utils/lib/ci/ci_result_parser.js:682:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async JobCommand.drain (/usr/local/lib/node_modules/node-core-utils/bin/ncu-ci:198:7)
    at async main (/usr/local/lib/node_modules/node-core-utils/bin/ncu-ci:369:3)
```

**Comment by codebytere** [comment]
@gengjiawen this'll be closed by https://github.com/nodejs/node-core-utils/pull/451

**Comment by gengjiawen** [comment]
> @gengjiawen this'll be closed by #451

But this has been runs by jenkins `QUIC CI: ci.nodejs.org/job/node-test-commit/39325`

**Comment by codebytere** [comment]
@gengjiawen ooh hmm ok i'll look more!

**Comment by codebytere** [comment]
perhaps a daft question but what's different about the QUIC CI? it looks like the same UI and tests being run but logically i assume there's something different in build params 🤔

**Comment by richardlau** [comment]
https://github.com/nodejs/node/pull/34086#issuecomment-650573553 doesn't have a node-test-pull-request run. The QUIC CI link is directly running node-test-commit because it uses non-standard config flags to build.

**Comment by gengjiawen** [comment]
> [nodejs/node#34086 (comment)](https://github.com/nodejs/node/pull/34086#issuecomment-650573553) doesn't have a node-test-pull-request run. The QUIC CI link is directly running node-test-commit because it uses non-standard config flags to build.

https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-ci.md

This page says 
```
Supported jobs:

node-test-pull-request
node-test-commit
benchmark-node-micro-benchmarks
```

Is it outdated ?

**Comment by codebytere** [comment]
@gengjiawen you need to run ` ncu-ci commit <jobid>` for `node-test-commit`
