### ISSUE TITLE
Creating a @nodejs/node-core-utils team?

### ISSUE THREAD

**Issue by codebytere** [nodejs/node-core-utils#462]
As mentioned by @mmarchini in an earlier PR, as there is a small consistent group of folks who review/open PRs on this repo I think it would simplify and streamline `@mentions` to create a `@nodejs/node-core-utils` team . What do you all think? I don't believe we need to follow any other protocol to make one once it's been determined who it would include, though I may be wrong!

cc'ing folks who may be interested:
 @mmarchini @targos @joyeecheung @richardlau @BridgeAR 

People slated for initial team (so far):
* @joyeecheung 
* @mmarchini
* @richardlau 
* @codebytere
* @targos
* @priyank-p

**Comment by richardlau** [comment]
Sounds good. Would be happy to be in the team if it is created.

**Comment by mmarchini** [comment]
I'd like to be in the team too.

Pinging all other folks who have individual write access to this repo (just in case):
@tniessen @Tiriel @refack @priyank-p @jasnell @apapirovski @addaleax

**Comment by jasnell** [comment]
I don't need it, but thank you! Great idea

**Comment by joyeecheung** [comment]
+1, also I guess we could complete https://github.com/nodejs/admin/issues/488 after the new team is created

**Comment by priyank-p** [comment]
I guess I'd like to be in team as well!

**Comment by codebytere** [comment]
I plan to make the initial team tomorrow if that sounds ok to you all!

**Comment by codebytere** [comment]
Done here: https://github.com/orgs/nodejs/teams/node-core-utils/members

**Comment by mmarchini** [comment]
leave it open until the cleanup sounds good

**Comment by joyeecheung** [comment]
Closing since we've done the clean up.
