### ISSUE TITLE
Fixes: and Refs: tags are pulled from PR description

### ISSUE THREAD

**Issue by addaleax** [nodejs/node-core-utils#470]
`git node land` seems to think that *any* `Fixes:` and `Refs:` tags it finds apply to *all* commits in a pull request. That’s unhelpful when there’s multiple commits in a PR, see e.g. https://github.com/nodejs/node/pull/34673. Is this intentional? If no, can we remove it? If yes, can we at least create a way to opt out?

**Comment by richardlau** [comment]
It probably was intentional. I kind of like not having Fixes/Refs in the commit metadata until landing otherwise referenced issues/PR's get spammed every time you update/force push rebase etc.

+1 for being optional for multi-commit PRs (maybe with a warning) or with an opt-out flag.

**Comment by codebytere** [comment]
+1 for warning and opt-out flag from me too - happy to pop up a PR if that seems like the path forward
