### ISSUE TITLE
Should retrieve more than the last 10 checkSuites

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-core-utils#476]
We have 12 check suites today on Node.js, which means we're not retrieving all suites to check if they passed (well, after #469 lands). We're retrieving 100 commits for the PR, which is unlikely to happen, so it's probably a good idea to shift from commits to checkSuites (maybe 25 commits / 40 check suites).

**Comment by targos** [comment]
Maybe still 50 commits? V8 updates often come close to 25.

**Comment by mmarchini** [comment]
Yeah, I'll tweak with it to use the graphql fetch limit (we'll probably go over 20 actions at some point). Although I'm not sure we use the commits (except the last) on any checks.

**Comment by codebytere** [comment]
@mmarchini mind if i do this?

**Comment by aduh95** [comment]
Fixed by https://github.com/nodejs/node-core-utils/commit/e98d72ef49d32d8b8a0605cce222cb8aaab8c128
