### ISSUE TITLE
Double-check that `commits(first: 100` returns the most recent 100 commits, and not the oldest 100

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-core-utils#477]
As title says, our PRCommits.gql query uses `first` for commits. I'm not sure if it fetches the newest or oldest 100 commits. If whoever implemented this already tested it and remember the answer, that's enough for me too :)

**Comment by targos** [comment]
I just tested with https://developer.github.com/v4/explorer for that PR: https://github.com/nodejs/node/pull/34752

With `first: 5`, it returns them from oldest to newest:
![image](https://user-images.githubusercontent.com/2352663/90309770-a713e080-deeb-11ea-8428-9d6f2d558325.png)

You can change to `last: 5` to get the most recent commits (still ordered from old to new):

![image](https://user-images.githubusercontent.com/2352663/90309801-e5110480-deeb-11ea-8b2d-e3f22cc777e4.png)

**Comment by codebytere** [comment]
Meaning we should swap to `last`?

**Comment by mmarchini** [comment]
> Meaning we should swap to last?

That's what I understood, yes
