### ISSUE TITLE
Changes to PR wait time and approval checks

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-core-utils#483]
If https://github.com/nodejs/node/pull/33879 lands the checks should be changed to:

- Require only one approval by default
  - Recommend (without blocking) to wait for a second approval
- Drop wait times as requirements (we can still add a suggestion to wait if the PR lands before 48h, but it should return success code and shouldn't block --yes)
- Check if 48h passed since the `wait-for-feedback` label was added

As a workaround for now, we can add a `.ncurc` file to nodejs/node, which will remove the wait time requirements, but handling the more fine grained cases suggested above probably makes more sense.

**Comment by aduh95** [comment]
https://github.com/nodejs/node/pull/33879 never landed, we can probably close this.
