### ISSUE TITLE
Publish permission for @nodejs/node-core-utils

### ISSUE THREAD

**Issue by mmarchini** [nodejs/node-core-utils#494]
We should add everyone on @nodejs/node-core-utils as maintainers on npm, so everyone can publish. Please share your npm username here :)

**Comment by richardlau** [comment]
I'm [richardlau](https://www.npmjs.com/~richardlau) on npm.

**Comment by targos** [comment]
@richardlau I added you

**Comment by priyank-p** [comment]
Mine is [priyankp](https://www.npmjs.com/~priyankp) though I don't think I need access :)

**Comment by joyeecheung** [comment]
I see that everyone is listed in https://www.npmjs.com/package/node-core-utils, so closing.
