### ISSUE TITLE
PSA: updated repository settings

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#509]
I reviewed the settings of this repository and did the following changes:
- Disabled Wikis: there was no wiki.
- Removed explicit write access from people who are already in the @nodejs/node-core-utils team. This shouldn't change their access.
- Added branch protection rules to the `master` branch:
  - Cannot be force-pushed
  - Require linear history (no merge commits)
  - Include administrators
  - Restrict who can push to matching branches: @nodejs/node-core-utils 
- Removed the AppVeyor webhook (we don't use AppVeyor anymore)
- Uninstalled the TravisCI GitHub app (we don't use TravisCI anymore)

Other things I didn't do but would like to change (thoughts?):
- Enable "Automatically delete head branches".
- Remove write access from people who are not in the @nodejs/node-core-utils team. They should be added to the team if they want to.
- Require at least one pull request review before merging.
- Require some status checks to pass before merging pull requests. This cannot be done yet because PRs open by the default `github-actions` token for releases do not trigger actions. We would need to set a custom access token for this (for example from nodejs-github-bot).

**Comment by joyeecheung** [comment]
> Enable "Automatically delete head branches".

I think it's probably better to leave that to the author (if it works as I understand, delete the branches in their own repo once the PR is merged)

> Remove write access from people who are not in the @nodejs/node-core-utils team. They should be added to the team if they want to.

SGTM

> Require at least one pull request review before merging.

Have we broken this before? But yes it's good to formalize it.

> Require some status checks to pass before merging pull requests. This cannot be done yet because PRs open by the default github-actions token for releases do not trigger actions. We would need to set a custom access token for this (for example from nodejs-github-bot).

SGTM, though I think we never really care about the coverage which tends to be red 🤣

**Comment by mmarchini** [comment]
> I think it's probably better to leave that to the author (if it works as I understand, delete the branches in their own repo once the PR is merged)

Deleted branches are never truly deleted and can be restored via GitHub UI. I don't remember if branches from forks are deleted or not though.
