### ISSUE TITLE
Can we disable the stale bot in this repository?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#521]
It's somewhat annoying that it keeps closing feature requests and there's no way for us to tell whether the issue was closed because it's fixed or because it's stale when we look at the issue list.

**Comment by joyeecheung** [comment]
Or maybe we can disable it on feature requests?

**Comment by targos** [comment]
Yes, I think we should disable the stale bot. I see no benefit of having it in this repository.

**Comment by targos** [comment]
> there's no way for us to tell whether the issue was closed because it's fixed or because it's stale when we look at the issue list.

Issues that were closed by the bot have the `stale` label.

**Comment by targos** [comment]
🙃
