### ISSUE TITLE
Get your Jenkins API token

### ISSUE THREAD

**Issue by ronag** [nodejs/node-core-utils#523]
I started getting the following error all of the sudden when running `git node land`.

```bash
node$ git node land 36635
Get your Jenkins API token in https://ci.nodejs.org/me/configure and run the following command to add it to your ncu config: ncu-config --global set jenkins_token TOKEN
```

What does it mean and how do I fix it?

**Comment by targos** [comment]
You need a personal Jenkins API token in `~/.ncurc`

**Comment by ronag** [comment]
@targos: it's there and has worked so far... :/

**Comment by targos** [comment]
Does it still not work? Maybe it was an issue with Jenkins and the `git-node land` script misinterpreted the response it got.

**Comment by ronag** [comment]
Still the same

**Comment by ronag** [comment]
I guess this is something other than `"token":` in ncurc. Has this recently changed? How do I get a "Jenkins Token"?

**Comment by targos** [comment]
`token` is for the GitHub token. The Jenkins token should be in `jenkins_token`.
I think the bug is in https://github.com/nodejs/node-core-utils/blob/3c862d1d298917287339b0d2d558b522bb2255cf/lib/auth.js#L71-L74.
If you authenticate with GitHub, the config file is completely rewritten and other keys such as `jenkins_token` can be lost.

**Comment by ronag** [comment]
How do I fix this?

**Comment by mmarchini** [comment]
https://ci.nodejs.org/

click on your name

![image](https://user-images.githubusercontent.com/4048656/103708814-26bb4e00-4f66-11eb-84d4-fd97f26522d3.png)

Click "Configure"

![image](https://user-images.githubusercontent.com/4048656/103708848-39358780-4f66-11eb-9b5b-58524fa62e81.png)

Click "Add new token"

![image](https://user-images.githubusercontent.com/4048656/103708870-42beef80-4f66-11eb-9570-a2addf4a081b.png)

Give it a name (like "node-core-utils") and click "Generate"

![image](https://user-images.githubusercontent.com/4048656/103708993-80237d00-4f66-11eb-9941-bc52c27de10e.png)

Copy the token (either select it and ctrl+C or click the copy icon right next to it)

![image](https://user-images.githubusercontent.com/4048656/103708943-66823580-4f66-11eb-8e43-828b481db8d6.png)

Run `ncu-config set jenkins_token "your-token"`
