### ISSUE TITLE
request to join node-core-utils team

### ISSUE THREAD

**Issue by Trott** [nodejs/node-core-utils#532]
I'd like to add myself to the node-core-utils team.  I also notice there is a pending request from @lundibundi in the GitHub interface. Is it OK to add myself and them? Or is there a process?

**Comment by richardlau** [comment]
+1. I'm not aware that a process was written down -- perhaps it should as there's also an implication that members of the team also be added as maintainers on npm: https://github.com/nodejs/node-core-utils/issues/494

**Comment by codebytere** [comment]
+1 from me as well!

**Comment by Trott** [comment]
OK, added @lundibundi and myself.
