### ISSUE TITLE
weird fixes url added in commit message

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#541]
Happened while landing https://github.com/nodejs/node/pull/37559

```
deps: upgrade npm to 7.6.0

PR-URL: https://github.com/nodejs/node/pull/37559
Fixes: https://github.com/hidden
Reviewed-By: Luigi Pinca <luigipinca@gmail.com>
Reviewed-By: Rich Trott <rtrott@gmail.com>
Reviewed-By: Michaël Zasso <targos@protonmail.com>
```

**Comment by richardlau** [comment]
FWIW it has picked it up from the issue description:

> * fix: hidden lockfiles were not respected on Node v10.0-10.12

**Comment by targos** [comment]
That's a duplicate of https://github.com/nodejs/node-core-utils/issues/233
