### ISSUE TITLE
publishing release 1.28.0

### ISSUE THREAD

**Issue by Trott** [nodejs/node-core-utils#564]
It looks like `release-please` published 1.28.0 to GitHub but not to npm? Any chance someone can publish it to npm and/or add me as a maintainer in npm so I can publish it?

@targos @mmarchini @joyeecheung @richardlau @codebytere

**Comment by targos** [comment]
It's published, and I added you as an owner.
Why did you cheat to avoid a v2.0.0?

**Comment by Trott** [comment]
> It's published, and I added you as an owner.
> Why did you cheat to avoid a v2.0.0?

I was only considering my change and not the other unpublished changes. My mistake!
