### ISSUE TITLE
Broken `git node release --prepare`?

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#686]
Not sure when it started, but it seems that the command now generates an invalid changelog file:
- Wrong format for the list of commits
- Doesn't update the versions table in `CHANGELOG_Vx.md`

Maybe related to https://github.com/nodejs/node-core-utils/pull/669
Refs: https://github.com/nodejs/node/pull/47087

**Comment by targos** [comment]
I fixed it. You can see the diff here: https://github.com/nodejs/node/compare/fd4b40e8edded567e941a12b92db78aadae5cec7..4221dce8a5b47087a331762cb0dfefb7b708ebf1

**Comment by richardlau** [comment]
> Not sure when it started, but it seems that the command now generates an invalid changelog file:
> 
> * Wrong format for the list of commits
> 
> Maybe related to #669 Refs: [nodejs/node#47087](https://github.com/nodejs/node/pull/47087)

Most likely. That PR updated changelog-maker -- changelog-maker@3 changed the default output format: https://github.com/nodejs/changelog-maker/pull/121.

**Comment by RafaelGSS** [comment]
Just opened two PRs that address this issue.
