### ISSUE TITLE
Ability to view the status of a PR

### ISSUE THREAD

**Issue by anonrig** [nodejs/node-core-utils#714]
It would be good to have a command like `git node view 11111` to see if a PR is ready to land, without calling `git node land 11111`.

**Comment by MoLow** [comment]
perhaps `git node land 111 --dry-run`

**Comment by targos** [comment]
Anything missing from `git node metadata 111` ?

**Comment by anonrig** [comment]
It seems `git node metadata` requires jenkins token, but `git node land` does not...

**Comment by targos** [comment]
I thought `git node land` required it as well. Anyway it's quite easy to create a jenkins token.
