### ISSUE TITLE
update requested staging branch before backporting in `git-node backport` 

### ISSUE THREAD

**Issue by rluvaton** [nodejs/node-core-utils#731]
Currently, if my `staging` branch is behind `upstream` one or not on the `staging` branch at all I will create a bad backport PR

so we should ask do you want to sync `staging` with `upstream` (if it's behind)

and we should checkout from the staging branch

**Comment by aduh95** [comment]
Why would you care about `main` for a backport PR? How can you know if it's behind without fetching the latest?

**Comment by rluvaton** [comment]
actually main is not that important

**Comment by rluvaton** [comment]
(working on this)
