### ISSUE TITLE
Fail to clone v8 on 20.7.0

### ISSUE THREAD

**Issue by H4ad** [nodejs/node-core-utils#743]
I tried:

```bash
git node v8 backport 6584b6 
```

But received:

```bash
⠋ Update local V8 clone
◼ V8 commit backport
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [ 'fetch', 'origin' ]
}

Node.js v20.7.0
```

From what I read from the code, the v8 folder should be created and then the v8 should be cloned.

I tried on node 20.1.0 and the clone works, so maybe there is some behavior that changed between 20.1.0 and 20.7.0

**Comment by aduh95** [comment]
The error message indicates that `git` is not available on the `$PATH`, I don't think it's related to the version of Node.js you use.

**Comment by richardlau** [comment]
@abmusse ran into a similar problem with current versions of node-core-utils. @H4ad can you try with node-core-utils@3.3.0 and see if the problems occurs with that version?

**Comment by H4ad** [comment]
@richardlau 3.3.0 works, 3.5.0 I got the same error.

**Comment by aduh95** [comment]
Probably related to https://github.com/nodejs/node-core-utils/pull/722, can you confirm wether you still see the error if you first clone the V8 repo manually and pass it to `--v8-dir`?

**Comment by H4ad** [comment]
@aduh95 If I first clone and then `--v8-dir`, it works without problem.
