### ISSUE TITLE
semver-major PR landing with a single approval

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/node-core-utils#747]
https://github.com/nodejs/node/pull/47769 is a semver-major PR and landed with a single approval as you can see below image:

<img width="327" alt="image" src="https://github.com/nodejs/node-core-utils/assets/26234614/94bb016b-fc9b-4538-8a6c-6e497dc318ac">

https://github.com/nodejs/node/commit/b40f0c30743aaecd57071f7be305df43e1083817 has:
```
Reviewed-By: Robert Nagy <ronagy@icloud.com>
Reviewed-By: Matteo Collina <matteo.collina@gmail.com>
Reviewed-By: Moshe Atlow <moshe@atlow.co.il>
```

And looking at https://github.com/nodejs/node/pull/47769 they did review and approve the PR at one point in time. But Robert was requested to review again in https://github.com/nodejs/node/pull/47769#event-9422015415 and Matteo was requested to review again in https://github.com/nodejs/node/pull/47769#event-9666713698.

I think there's a bug in `git node land` that consider the first approval only.

**Comment by aduh95** [comment]
It's a duplicate of https://github.com/nodejs/node-core-utils/issues/677, as I said in https://github.com/nodejs/node-core-utils/issues/677#issuecomment-1587671668 I would argue this is working as expected.

**Comment by RafaelGSS** [comment]
Closing in favor of #677.
