### ISSUE TITLE
Add tests for cross-repository/cross-owner fixes

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/node-core-utils#75]
Opening a separate issue so it does not get buried...

<del>After https://github.com/joyeecheung/node-core-utils/pull/70 we've fixed the fixes parsing bug (kudos to @apapirovski !) but now it would skip cross-repo fixes. I think we can reliably get the fixes url with `getRefUrlFromOP()` which parses the HTML to get the link. </del>

It works! But would need some tests to make sure it does not regress..

**Comment by joyeecheung** [comment]
Ah, looking at it a bit deeper I think this also existed before the fix, and it would skip both cross-owner and cross-repo fixes.

**Comment by joyeecheung** [comment]
Ah wait, after a few tests I think this works properly already because it tests `/^#/` so cross references would be skipped. Still worth adding some tests to make sure it does not regress though.

**Comment by ryzokuken** [comment]
@joyeecheung what exactly are we testing for? Let me know if I could help.

**Comment by joyeecheung** [comment]
@ryzokuken We need to test that PRs with the message `fixes https://github.com/joyeecheung/node-core-utils/issues/123` will still have a line `Fixes: https://github.com/joyeecheung/node-core-utils/issues/123` in the metadata generated by `lib/metadata_gen.js`.

**Comment by ryzokuken** [comment]
@joyeecheung there's already a file that contains a single test for metadata_gen. Should I add to that file or make another one and name both appropriately?

**Comment by ryzokuken** [comment]
@joyeecheung take a look at #197
