### ISSUE TITLE
CI fails on Node.js 21

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#752]
See https://github.com/nodejs/node-core-utils/actions/runs/6847526575/job/18615958948?pr=751

**Comment by targos** [comment]
@nodejs/test_runner Is there a way to execute the test runner with arguments that work in all supported Node.js versions?

**Comment by targos** [comment]
@MoLow Do you know of a solution?

**Comment by MoLow** [comment]
not a good one.
I would try changing the command based on the node version,
we can also run `node --test $(find . -name 'test/unit/**.js' | tr '\n' ' ')` which will be compatible for all versions

**Comment by targos** [comment]
This is unfortunate. Isn't it a big issue for adoption of the test runner by projects that want to support all release lines?

**Comment by MoLow** [comment]
It probably is, we should have probably thought about that - although this change was a semver major change, and was necessary since it made it possibe to run typescript tests or tests other then the default pattern

**Comment by aduh95** [comment]
I guess we could backport it behind a `--experimental-glob-in-test-runner` flag or something like that

**Comment by ljharb** [comment]
Major changes for a test runner built into the platform will always cause this problem; the only solution is to never have them, or, not have a test runner that’s built in.
