### ISSUE TITLE
release-please is broken

### ISSUE THREAD

**Issue by targos** [nodejs/node-core-utils#845]
https://github.com/nodejs/node-core-utils/actions/runs/10579923839/job/29313534027

> ✖ RequestError [HttpError]: Error creating Pull Request: Resource not accessible by integration

**Comment by aduh95** [comment]
We might need to create a bot token – which might be desirable anyway so CI is run on the release PR

**Comment by RedYetiDev** [comment]
Couldn't this also be done via GitHub Actions with the `releases: write` permissions?

**Comment by joyeecheung** [comment]
I ran into a similar message when I was updating the reliability workflow and it seems adding the corresponding permission in the workflow file is enough (so no need to create a separate token, just grant new permission to the GITHUB_TOKEN via the workflow): https://github.com/nodejs/reliability/commit/1e658e9e7f15694fc45ae76165bc6682c706d836

**Comment by RedYetiDev** [comment]
https://github.com/nodejs/node-core-utils/pull/848 would work?
